<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Invoices extends MY_Controller {
 public function __construct(){parent::__construct();$this->load->model('Finance_model','finance');}
 public function index(){$this->require_login(array('Finance','PIC Project'));$this->render('invoices/index',array('title'=>'Invoice','rows'=>$this->finance->invoice_list()));}
 public function create(){$this->require_login(array('Finance'));if($this->input->method()==='post'){$this->save();redirect('invoices');}$this->form();}
 public function edit($id){$this->require_login(array('Finance'));$i=$this->db->where('invoice_id',$id)->get('invoices')->row();if(!$i||$i->status!=='Draft'){flash('error','Hanya Invoice Draft yang dapat diubah.');redirect('invoices');}if($this->input->method()==='post'){$this->db->where('invoice_id',$id)->update('invoices',array('invoice_date'=>$this->input->post('invoice_date')));flash('success','Invoice diperbarui.');redirect('invoices');}$this->form($i);}
 public function status($id){$this->require_login(array('Finance'));$status=$this->input->post('status');$note=$this->input->post('reject_note',TRUE);if($status==='Rejected'&&!$note){flash('error','Alasan reject wajib diisi.');}else{$this->db->where('invoice_id',$id)->update('invoices',array('status'=>$status,'reject_note'=>$note));flash('success','Status Invoice diperbarui.');}redirect('invoices');}
 private function form($invoice=NULL){$items=$this->db->select('i.*,p.po_number,d.unit_price,m.part_number,m.description')->from('purchase_order_items i')->join('purchase_orders p','p.po_id=i.po_id')->join('service_order_details d','d.so_detail_id=i.so_detail_id')->join('boqs b','b.boq_id=d.boq_id')->join('master_items m','m.master_item_id=b.master_item_id')->get()->result();$this->render('invoices/form',array('title'=>$invoice?'Edit Invoice':'Buat Invoice','invoice'=>$invoice,'pos'=>$this->db->order_by('po_number')->get('purchase_orders')->result(),'items'=>$items));}
 private function save(){$po=$this->input->post('po_id');$items=$this->finance->po_items($po);$valid=array();foreach($items as $i)$valid[$i->po_item_id]=$i;foreach((array)$this->input->post('qty') as $item=>$qty)if((float)$qty>0&&!isset($valid[$item])){flash('error','Item invoice tidak sesuai dengan PO.');return;}$this->db->trans_start();$this->db->insert('invoices',array('po_id'=>$po,'created_by'=>$this->session->userdata('user_id'),'invoice_number'=>$this->input->post('invoice_number',TRUE),'invoice_date'=>$this->input->post('invoice_date'),'total_invoice'=>0,'created_at'=>date('Y-m-d H:i:s')));$id=$this->db->insert_id();$total=0;foreach((array)$this->input->post('qty') as $poitem=>$qty){if((float)$qty<=0)continue;$item=$valid[$poitem];$sub=$qty*$item->unit_price;$total+=$sub;$this->db->insert('invoice_details',array('invoice_id'=>$id,'po_item_id'=>$poitem,'qty'=>$qty,'subtotal'=>$sub));}$this->db->where('invoice_id',$id)->update('invoices',array('total_invoice'=>$total));$this->db->trans_complete();flash('success','Invoice disimpan sebagai Draft.');}
}
