<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Purchaseorders extends MY_Controller {
 public function __construct(){parent::__construct();$this->load->model('Finance_model','finance');}
 public function index(){$this->require_login(array('PIC Project','Finance'));$this->render('purchase_orders/index',array('title'=>'Purchase Order','rows'=>$this->finance->po_list()));}
 public function create(){$this->require_login(array('PIC Project'));if($this->input->method()==='post'){$this->save();redirect('purchase-orders');}$this->form();}
 public function import(){$this->require_login(array('PIC Project'));$this->form(NULL, TRUE);}
 public function edit($id){$this->require_login(array('PIC Project'));if($this->db->where('po_id',$id)->count_all_results('invoices')){flash('error','PO yang sudah dipakai Invoice tidak dapat diubah.');redirect('purchase-orders');}$po=$this->db->where('po_id',$id)->get('purchase_orders')->row();if($this->input->method()==='post'){$this->db->where('po_id',$id)->update('purchase_orders',array('po_date'=>$this->input->post('po_date'),'vendor'=>$this->input->post('vendor',TRUE),'status'=>$this->input->post('status')));flash('success','Header PO diperbarui.');redirect('purchase-orders');}$this->form($po);}
 private function form($po=NULL,$is_import=FALSE){$this->render('purchase_orders/form',array('title'=>$po?'Edit Purchase Order':($is_import?'Import Purchase Order BP':'Buat Purchase Order'),'po'=>$po,'is_import'=>$is_import,'details'=>$this->finance->available_so_details()));}
 private function save(){$remaining=array();foreach($this->finance->available_so_details() as $d)$remaining[$d->so_detail_id]=$d->remaining;foreach((array)$this->input->post('qty') as $detail=>$qty)if((float)$qty>0&&(!isset($remaining[$detail])||$qty>$remaining[$detail])){flash('error','Qty PO melebihi saldo budget SO.');return;}$source=NULL;if(!empty($_FILES['po_pdf']['name'])){$config=array('upload_path'=>FCPATH.'uploads/po/','allowed_types'=>'pdf','max_size'=>5120,'encrypt_name'=>TRUE);$this->load->library('upload',$config);if(!$this->upload->do_upload('po_pdf')){flash('error',$this->upload->display_errors('',''));return;}$source='uploads/po/'.$this->upload->data('file_name');}$this->db->trans_start();$this->db->insert('purchase_orders',array('created_by'=>$this->session->userdata('user_id'),'po_number'=>$this->input->post('po_number',TRUE),'po_date'=>$this->input->post('po_date'),'vendor'=>$this->input->post('vendor',TRUE),'status'=>'Draft','source_file'=>$source,'created_at'=>date('Y-m-d H:i:s')));$id=$this->db->insert_id();foreach((array)$this->input->post('qty') as $detail=>$qty){if((float)$qty<=0)continue;$d=$this->db->where('so_detail_id',$detail)->get('service_order_details')->row();$this->db->insert('purchase_order_items',array('po_id'=>$id,'so_detail_id'=>$detail,'qty'=>$qty,'additional_description'=>$this->input->post('notes['.$detail.']',TRUE),'subtotal'=>$qty*$d->unit_price));}$this->db->trans_complete();flash($this->db->trans_status()?'success':'error',$this->db->trans_status()?'PO berhasil dibuat.':'PO gagal disimpan.');}
}
