<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Serviceorders extends MY_Controller {
 public function __construct(){parent::__construct();$this->load->model('Finance_model','finance');}
 public function index(){$this->require_login(array('PIC Project','Finance'));$this->render('service_orders/index',array('title'=>'Service Order','rows'=>$this->finance->so_list()));}
 public function create(){$this->require_login(array('PIC Project'));if($this->input->method()==='post'){$this->save();redirect('service-orders');}$this->form();}
 public function edit($id){$this->require_login(array('PIC Project'));$so=$this->db->where('so_id',$id)->get('service_orders')->row();if(!$so||$so->status!=='Draft'){flash('error','Hanya SO Draft yang dapat diubah.');redirect('service-orders');}if($this->input->method()==='post'){$this->db->where('so_id',$id)->update('service_orders',array('activity'=>$this->input->post('activity',TRUE),'work_period'=>$this->input->post('work_period',TRUE),'cost_centre_id'=>$this->input->post('cost_centre_id')));flash('success','Header SO diperbarui.');redirect('service-orders');}$this->form($so);}
 public function approve($id){$this->require_login(array('PIC Project'));$so=$this->db->where('so_id',$id)->get('service_orders')->row();if($so&&$so->status==='Draft'){$this->db->where('so_id',$id)->update('service_orders',array('status'=>'Approved','approved_at'=>date('Y-m-d H:i:s')));flash('success','SO approved dan terkunci.');}redirect('service-orders');}
 private function form($so=NULL){$this->render('service_orders/form',array('title'=>$so?'Edit Service Order':'Buat Service Order','so'=>$so,'agreements'=>$this->finance->options('master_agreements','agreement_id','agreement_number',array('status'=>'Active')),'centres'=>$this->finance->options('cost_centres','cost_centre_id','cost_centre_name'),'boqs'=>$this->db->select('b.*,m.part_number,m.description')->from('boqs b')->join('master_items m','m.master_item_id=b.master_item_id')->get()->result()));}
 private function save(){$this->db->trans_start();$agreement=$this->input->post('agreement_id');$so=array('agreement_id'=>$agreement,'cost_centre_id'=>$this->input->post('cost_centre_id'),'created_by'=>$this->session->userdata('user_id'),'so_number'=>'SO-'.date('Ymd').'-'.str_pad($this->db->count_all('service_orders')+1,4,'0',STR_PAD_LEFT),'activity'=>$this->input->post('activity',TRUE),'work_period'=>$this->input->post('work_period',TRUE),'total_budget'=>0,'created_at'=>date('Y-m-d H:i:s'));$this->db->insert('service_orders',$so);$id=$this->db->insert_id();$total=0;foreach((array)$this->input->post('qty') as $boq=>$qty){if((float)$qty<=0)continue;$b=$this->db->where(array('boq_id'=>$boq,'agreement_id'=>$agreement))->get('boqs')->row();if(!$b)continue;$sub=$qty*$b->unit_price;$total+=$sub;$this->db->insert('service_order_details',array('so_id'=>$id,'boq_id'=>$boq,'qty_plan'=>$qty,'unit_price'=>$b->unit_price,'subtotal'=>$sub));}$this->db->where('so_id',$id)->update('service_orders',array('total_budget'=>$total));$this->db->trans_complete();flash($this->db->trans_status()?'success':'error',$this->db->trans_status()?'SO berhasil dibuat.':'SO gagal disimpan.');}
}
